FROM nginx:alpine
#RUN apt-get update && apt-get upgrade -y && apt-get clean

# minha-app
#copy local static dir files to nginx container
# app name : minha-app
#
#RUN apt-get update -y
COPY static-content /usr/share/nginx/html