name: build docker image

on:
  push:
    paths:
      - 'app/**'
    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 1 - Build the Docker image for Minha-app
      run: |
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io
        ls -la
        cd app
        
        docker build -t hello1 .

        echo "change TAG from $GITHUB_SHA and push"
        docker tag hello1 rfdnet/hello1:$GITHUB_SHA
        docker push rfdnet/hello1:$GITHUB_SHA

        echo "change TAG from $GITHUB_SHA to latest and push"
        docker tag rfdnet/hello1:$GITHUB_SHA rfdnet/hello1:latest
        docker push rfdnet/hello1:latest
        
        
        echo "Done"

    - name: 2 - docker image scan
      uses: anchore/scan-action@v3
      with:
        image: "rfdnet/hello1:latest"
        severity-cutoff: critical