name: deploy to cluster Demo - manual trigger
run-name: ${{ github.actor }} is running a deploy on cluster Demo
on: 
  workflow_dispatch

jobs:
  deploy:
    name: deploy to cluster Demo
    runs-on: ubuntu-latest
    steps:
  

    - name: 1 - Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: 2 - Install and configure kubectl
      run: |
        aws eks --region us-west-2 update-kubeconfig --name demo
        kubectl get svc
        kubectl set image deployment/nginx nginx=rfdnet/hello1:latest