name: Deploy to k8s cluster DEMO


on: 
  workflow_dispatch:
    paths:
      - 'app/**'





jobs:

  deploy:
    name: Deploy to cluster Demo - manual trigger
    runs-on: ubuntu-latest
    steps:
  
    - name: 1 - Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: 2 - Deploy latest image
      run: |
        aws eks --region us-west-2 update-kubeconfig --name demo
        echo "Running kubectl"
        kubectl set image deployment/nginx nginx=rfdnet/hello1:$GITHUB_SHA