name: deploy to cluster Demo - manual trigger
run-name: ${{ github.actor }} is running a deploy on cluster Demo
on: 
  workflow_dispatch

jobs:
  deploy:
    name: deploy to cluster Demo - manual trigger
    runs-on: ubuntu-latest
    steps:
  
    - name: 1 - Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: 2 - docker image scan
      uses: anchore/scan-action@v3
      with:
        image: "rfdnet/hello1:$GITHUB_SHA"
        
    - name: 3 - show new pod(s)
      run: |
        kubectl get po
        echo "listing LB"
        echo "Done"