name: deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
    
    - name: Configure AWS Credentials
    - uses: actions/checkout@v3
      run: |
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io
        ls -la
        #aws eks --region us-west-2 update-kubeconfig --name demo
        pwd
        echo "ok"
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}