name: deploy

on:
  - push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - uses: actions/checkout@v2
      - name: Run kubectl
        uses: nikosch86/github-action-eks-kubectl@main
        with:
          command: "apply deployment.yaml"
        env:
          EKS_CLUSTER: demo