name: Destroy terraform resources on the folder infra


on:
  workflow_dispatch:
    inputs:
      dir:
        description: 'Directory with resources to be destroyed'
        required: true
        default: 'infra'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  destroy-dev:
    name: 'terraform destroy dev'
    runs-on: ubuntu-latest
    env:
      TF_WORKING_DIR: ${{ github.event.inputs.dir }}

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: 1 - Checkout
        uses: actions/checkout@v2

      - name: 2 - Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.5

      - name: 3 - Terraform fmt
        id: fmt
        run: terraform fmt -check

      - name: 4 - Terraform Init
        id: init
        run: terraform init -reconfigure -backend=true -backend-config="config/dev/backend.hcl"

      - name: 5 - Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: 6 - Terraform Destroy
        run: | 
         terraform state rm aws_dynamodb_table.terraform_locks
         terraform state rm aws_s3_bucket.terraform_state
         terraform destroy -auto-approve -var-file="config/dev/terraform.tfvars"

  destroy-prod:
    name: 'terraform destroy prod'
    runs-on: ubuntu-latest
    env:
      TF_WORKING_DIR: ${{ github.event.inputs.dir }}

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: 1 - Checkout
        uses: actions/checkout@v2

      - name: 2 - Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.5

      - name: 3 - Terraform fmt
        id: fmt
        run: terraform fmt -check

      - name: 4 - Terraform Init
        id: init
        run: terraform init -backend-config="config/prod/backend.hcl"

      - name: 5 - Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: 6 - Terraform Destroy
        run: terraform destroy -auto-approve -var-file="config/dev/terraform.tfvars"