name: Create terraform plan on folder infra
run-name: ${{ github.actor }} is running a TF plan

on:
  workflow_dispatch:
    paths:
      - 'infra/**'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:

  plan-prod:
    name: 'terraform plan prod'
    runs-on: ubuntu-latest
    env:
      TF_WORKING_DIR: 'infra'

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: 1 - Checkout
        uses: actions/checkout@v2

      - name: 2 - Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.5

      - name: 3 -Terraform fmt
        id: fmt
        run: terraform fmt
             
      - name: 4 - Terraform init
        id: init
        run: terraform init -reconfigure -backend=true -backend-config="config/prod/backend.hcl"

      - name: 5 - Terraform validate
        id: validate
        run: terraform validate -no-color

      - name: 6 - Terraform Plan
        id: planprod
        run: 
          #terraform init -reconfigure -backend=true -backend-config="config/prod/backend.hcl"
          terraform plan