name: TF PLAN


on:
  pull_request:
    paths:
      - 'infra/**'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:

  plan-prod:
    name: 'terraform plan PROD'
    runs-on: ubuntu-latest
    env:
      TF_WORKING_DIR: 'infra'

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: 1 - Checkout
        uses: actions/checkout@v2

      - name: 2 - Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 0.15.5

      - name: 3 -Terraform fmt
        id: fmt
        run: terraform fmt
             
      - name: 4 - Terraform init
        id: init
        run: terraform init -reconfigure -backend=true -backend-config="config/prod/backend.hcl"

      - name: 5 - Terraform validate
        id: validate
        run: terraform validate -no-color
      
      - name: 6 - Terraform Plan
        id: plan
        run: |
          terraform plan -input=false -no-color -var-file="config/prod/terraform.tfvars"


      # github integration with PR
      - uses: actions/github-script@v7
        with:
          script: |
            // Get a list of all issues created by the PR opener
            // See: https://octokit.github.io/rest.js/#pagination
            const creator = context.payload.sender.login
            const opts = github.rest.issues.listForRepo.endpoint.merge({
              ...context.issue,
              creator,
              state: 'all'
            })
            const issues = await github.paginate(opts)

            for (const issue of issues) {
              if (issue.number === context.issue.number) {
                continue
              }

              if (issue.pull_request) {
                return // Creator is already a contributor.
              }
            }

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `**Welcome**, new contributor!

                Please make sure you've read our [contributing guide](CONTRIBUTING.md) and we look forward to reviewing your Pull request shortly ✨`
            })

  plan-dev:
    name: 'terraform plan DEV'
    runs-on: ubuntu-latest
    env:
      TF_WORKING_DIR: 'infra'

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: 1 - Checkout
        uses: actions/checkout@v2

      - name: 2 - Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 0.15.5

      - name: 3 -Terraform fmt
        id: fmt
        run: terraform fmt
             
      - name: 4 - Terraform init
        id: init
        run: terraform init -reconfigure -backend=true -backend-config="config/dev/backend.hcl"

      - name: 5 - Terraform validate
        id: validate
        run: terraform validate -no-color
      
      - name: 6 - Terraform Plan
        id: plan
        run: |
          terraform plan -input=false -no-color -var-file="config/dev/terraform.tfvars"